### ISSUE TITLE
Unsupported Protocol Scheme

### ISSUE THREAD

**Issue by Sicks3c** [Ph33rr/cirrusgo#4]
Hello

Thank you tremendously for the tool
upon running on my target I came across this issue
<img width="777" alt="Screen Shot 2022-07-12 at 10 45 19" src="https://user-images.githubusercontent.com/32225186/178462000-a01dc166-a8c3-4119-afd6-33aa8d65bdf3.png">

Tested on `Mac / Ubuntu` Same issue

**Comment by Ph33rr** [comment]
thank you 
https://github.com/Ph33rr/cirrusgo/commit/188e3eae2e8fa7574a14d6bc639cd7801805f7d0
