### ISSUE TITLE
An Error Occured invalid URL escape "%Ma"

### ISSUE THREAD

**Issue by marz-hunter** [Ph33rr/cirrusgo#7]
run `cirrusgo salesforce -u https://aura.co -cw`

```
[WRN] Use with caution. You are responsible for your actions
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[VLN] https://aura.co/aura Vulnerable
[VLN] https://aura.co/sfsites/aura Vulnerable
[vulnerable Endpoint] [/aura,/sfsites/aura]
2022/07/29 23:08:12 An Error Occured invalid URL escape "%Ma"
```

error:

`2022/07/29 23:08:12 An Error Occured invalid URL escape "%Ma`

Go Version
`go version`
`go version go1.18 linux/amd64`

OS

Ubuntu 18

**Comment by marz-hunter** [comment]
options `-lobj` `-gobj` also shows the same error

**Comment by Ph33rr** [comment]
command:

curl -v https://yyyy.com

copy 

headers and body here

**Comment by marz-hunter** [comment]
`cirrusgo salesforce -u https://aaa -gobj`

**Comment by Ph33rr** [comment]
command

curl -X POST https://aaaa/aura -d " "

response : 
```
{"event":{"descriptor":"markup://aura:invalidSession","attributes":{"values":{}},"eventDef":{"descriptor":"markup://aura:invalidSession","t":"APPLICATION","xs":"I","a":{"newToken":["newToken","aura://String","I",false]}}},"exceptionMessage":"Guest user access is not allowed","exceptionEvent":true}
```

endpoint vuln

but 

Guest user access is not allowed 

check here 

#6 


Thanks for sharing this error
